### ISSUE TITLE
Uncaught exception: ReferenceError: Security violation only in Opera

### ISSUE THREAD

**Issue by babake2000** [maccman/juggernaut#16]
I continue to receive the error below in opera after installing the latest of socket.io-node and juggernaut. IE 8, FF, Chrome all connect. opera is the only client I have tested so far that is not. 

Uncaught exception: ReferenceError: Security violation

Error thrown at line 1, column 24211 in <anonymous function: b.prototype._get>() in http://204.236.224.20:8080/application.js:
    this._xhr.send()
called from line 1, column 12221 in <anonymous function: b.prototype.connect>() in http://204.236.224.20:8080/application.js:
    this._get();
called from line 1, column 23558 in <anonymous function: b.prototype.connect>() in http://204.236.224.20:8080/application.js:
    io.Transport.XHR.prototype.connect.call(this)
called via Function.prototype.call() from line 1, column 30910 in <anonymous function: a.prototype.connect>() in http://204.236.224.20:8080/application.js:
    this.transport.connect();
called from line 1, column 84704 in <anonymous function: Juggernaut.fn.connect>() in http://204.236.224.20:8080/application.js:
    this.socket.connect()
called from line 1, column 85128 in <anonymous function: Juggernaut.fn.subscribe>(b, c) in http://204.236.224.20:8080/application.js:
    this.connect()
called from line 4, column 8 in http://204.236.224.20:3000/chat/enter_room/Yoruba_room:
    jug.subscribe("Yoruba_room", function(data){

**Comment by maccman** [comment]
I think I've tackled this in the google group - it's a COR header issue. 

I've fixed it in my own version of Socket.IO-Node:

npm install http://cl.ly/2dgx/content

**Comment by babake2000** [comment]
Hey Alex, it still doesn't work for me on opera. Earlier today, I removed Socket.IO-Node install that I had, did the npm install http://cl.ly/2dgx/content and tried on opera, but it still came up with the error (IE and Chrome fine, just Opera). If I go to the sample on 8080, it's fine in all browsers, but with my web server on port 3000, it still came back with the error above.

**Comment by maccman** [comment]
Ah ok. Maybe worth checking whether Opera has COR support?

**Comment by babake2000** [comment]
I found this in a forum about CORS support:

Comment by oyvindkinsey — May 26, 2010 
Right,

Those browsers are IE8+, FF3.5+, Saf4, and Chrome. No Opera yet.

So, does this place a limitation on how much support one can provide for using the Juggernaut 2 with rails, or do you know any alternative approach that could avoid the CORS situation.

**Comment by maccman** [comment]
Yes, just use the flash transport with Opera.
