### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by romanenko** [maccman/juggernaut#51]
I'm using Ubuntu 10.04 on my developer machine and Debian Lenny on server. I have node 0.4.3, npm, redis 2.2.2. And in both places I am encountering this error.

When i do
    > git clone https://github.com/maccman/juggernaut.git --recursive 
    > cd juggernaut
    > node server.js

Everything works fine.

But, when I try to run juggernaut with RunIt as daemon
    "exec /usr/local/bin/node /opt/juggernaut/derver.js"

juggernaut is running and I get 404 errors
    25 Mar 07:36:46 - socket.io ready - accepting connections
    > Error serving / - Not Found
    > Error serving /favicon.ico - Not Found
    > Error serving / - Not Found
    > Error serving /favicon.ico - Not Found

application.js is also unreachable 
    > Error serving /application.js - Not Found

And when I simply install juggernaut with npm, and run 
    > juggernaut
    > Error serving / - Not Found
    > Error serving /favicon.ico - Not Found

..I also get this strange 404 errors.

Tried with latest node 0.5 pre -- and the same thing.
Tried changing the PORT env variable -- no effect.

Just an idea: I think this is because the "node-static" dependency, because I read somewhere about 404 errors before.. but I don't know how to fix it.

**Comment by ghost** [comment]
Have the same error!

**Comment by maccman** [comment]
That's to do with the node-static version. It has been fixed in the latest
version of Juggernaut.

Follow the new installations instruction using npm.

Thanks,
Alex

On Fri, Mar 25, 2011 at 5:46 PM, perfecto <
reply@reply.github.com>wrote:

> I'm using Ubuntu 10.04 on my developer machine and Debian Lenny on server.
> I have node 0.4.3, npm, redis 2.2.2. And in both places I am encountering
> this error.
> 
> When i do
> 
> > git clone https://github.com/maccman/juggernaut.git --recursive
> > cd juggernaut
> > node server.js
> 
> Everything works fine.
> 
> But, when I try to run juggernaut with RunIt as daemon
>    "exec /usr/local/bin/node /opt/juggernaut/derver.js"
> 
> juggernaut is running and I get 404 errors
>    25 Mar 07:36:46 - socket.io ready - accepting connections
> 
> > Error serving / - Not Found
> > Error serving /favicon.ico - Not Found
> > Error serving / - Not Found
> > Error serving /favicon.ico - Not Found
> 
> application.js is also unreachable
> 
> > Error serving /application.js - Not Found
> 
> And when I simply install juggernaut with npm, and run
> 
> > juggernaut
> > Error serving / - Not Found
> > Error serving /favicon.ico - Not Found
> 
> ..I also get this strange 404 errors.
> 
> Tried with latest node 0.5 pre -- and the same thing.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/51

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by romanenko** [comment]
Yes, I installed juggernaut using rpm.
juggernaut 2.0.2

And still the same problem. Even tried to reinstall now.

**Comment by christianhager** [comment]
I hacked this by giving node-static the absolute path to the public folder in server.js
var fileServer = new nstatic.Server("/usr/local/lib/node/.npm/juggernaut/2.0.2/package/public");

**Comment by romanenko** [comment]
Yep! It works with christianhager's monkey patch. How to fix it in the repository?

**Comment by maccman** [comment]
If you submit the patch to node-static, and a new version is released, than
it'll be automatically fixed with Juggernaut.

On Sun, Mar 27, 2011 at 6:47 PM, perfecto <
reply@reply.github.com>wrote:

> Yep! It works with christianhager's monkey patch. How to fix it in the
> repository?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/51#comment_922013

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by prabgupt** [comment]
I too am facing the same issue after installing latest juggernaut using npm. I also tried christianhager's hack but unfortunately it's not working for me. I'm getting following error after applying the hack and accessing localhost:8080. Even node server gets crashed afterwards:

> Error serving /application.js - undefined

http.js:832
  var statusLine = 'HTTP/1.1 ' + statusCode.toString() + ' ' +
                                            ^
TypeError: Cannot call method 'toString' of null
    at ServerResponse.writeHead (http.js:832:45)
    at /usr/local/lib/node/.npm/juggernaut/2.0.2/package/lib/juggernaut/server.js:29:22
    at [object Object].finish (/usr/local/lib/node/.npm/node-static/0.5.3/package/lib/node-static.js:103:13)
    at /usr/local/lib/node/.npm/node-static/0.5.3/package/lib/node-static.js:165:14
    at /usr/local/lib/node/.npm/node-static/0.5.3/package/lib/node-static.js:215:33
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/node-static/0.5.3/package/lib/node-static.js:245:17)
    at [object Object].emit (events.js:64:17)
    at fs.js:809:12

**Comment by prabgupt** [comment]
ok.. I got it working now without modifying any code, by just executing "sudo juggernaut" from inside /usr/local/lib/node/.npm/juggernaut/2.0.2/package/. I wonder why christianhager's hack didn't work for it. Nevertheless, thanks for pointing us in the right direction :)

Alex,
Not sure if this is an issue with node-static or in juggernaut itself. In server.js, a relative path is passed to node-static and I think that is why either running the command from inside juggernaut or passing an absolute location is solving this problem. Anyways it would be better to include this in ReadMe Doc meanwhile this issue gets fixed.

Thanks

**Comment by maccman** [comment]
Should be fixed now - update via npm and give it another shot.

Cheers!
Alex

On Wed, Mar 30, 2011 at 7:18 AM, prabgupt <
reply@reply.github.com>wrote:

> ok.. I got it working now without modifying any code, by just executing
> "sudo juggernaut" from inside
> /usr/local/lib/node/.npm/juggernaut/2.0.2/package/. I wonder why
> christianhager's hack didn't work for it. Nevertheless, thanks for pointing
> us in the right direction :)
> 
> Alex,
> Not sure if this is an issue with node-static or in juggernaut itself. In
> server.js, a relative path is passed to node-static and I think that is why
> either running the command from inside juggernaut or passing an absolute
> location is solving this problem. Anyways it would be better to include this
> in ReadMe Doc meanwhile this issue gets fixed.
> 
> Thanks
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maccman/juggernaut/issues/51#comment_932278

## 

Alex MacCaw

(415) 513-0975
@maccman

http://alexmaccaw.co.uk | http://www.leadthinking.com | http://socialmod.com

**Comment by romanenko** [comment]
It works! Thank you!
